services:
  - type: web
    name: grace-tc-geology-explorer
    runtime: node
    plan: free
    buildCommand: pip3 install netCDF4 numpy && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: EARTHDATA_USER
        value: kchgeo
      - key: EARTHDATA_PASS
        value: 1MoyaleHydro!
      - key: ANTHROPIC_API_KEY
        sync: false   # set this manually in Render dashboard as a secret
